version: 2.1
#orbs:
#  terraform: circleci/terraform@2.0.0
jobs:
  single-job-lifecycle:
#    executor: terraform/default
    docker:
      - image: alpine:latest
    steps:
    - checkout
#    - terraform/init:
#        path: ./
    # - terraform/validate:
    #     path: ./
    # - terraform/fmt:
    #     path: ./
    # - terraform/apply:
    #     path: ./
    #     var: cluster_id=${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BUILD_NUM},random_network_num=
    - run:
        name: System Test
        command: |
          echo "Hash: $(echo $CIRCLE_SHA1)"
          echo "Cluster: $(echo $CIRCLE_PROJECT_REPONAME-$CIRCLE_BUILD_NUM)"
    # - terraform/destroy:
    #     path: ./
    working_directory: ~/project/testing
workflows:
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle